apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "Name of ConfigMap is required" .Values.name}}-configmap
data:
  myValue: "Hello World"
  drink: {{ .Values.drink | upper | quote }}
  food: {{ .Values.food | title | quote }}